apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: paul.bourhis@bhs-consulting.com
        privateKeySecretRef:
        name: letsencrypt-staging
        solvers:
        - dns01:
            rfc2136:
                nameserver: <address of authoritative nameserver configured above>
                tsigKeyName: <key name used in `dnssec-keygen`, use something semantically meaningful in both environments>
                tsigAlgorithm: HMACSHA512 // should be matched to the algo you chose in `dnssec-keygen` when creating the key
                tsigSecretSecretRef:
                    name: <the name of the k8s secret holding the TSIG key.. not the key itself!>
                    key: <name of the key *inside* the secret>